server:
  port: 8000


eureka:
  client:
    service-url:
      defalutZone: http://127.0.0.1:8761/eureka

  instance: # 一般配置在client中
    prefer-ip-address: true # 是否将自己的ip注册到eureka中(公网使用),默认是false，注册是主机名
    ip-address: 127.0.0.1 # 设置当前实例的IP地址
    # 实例的id --> 主机名:项目名称:端口号
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}


spring:
  application:
    name: spring-cloud-consumer

spring-cloud-provider: # 生产者服务的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 负载均衡策略（随机）
